server:
  Port: 8080
  RunMode: debug
logger:
  filePath: logs/logs.log
  encoding: json
  level: debug
  loggerName: Zap
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5433
  user: postgres
  password: 12345678
  dbName: restaurant_db
  sslMode: disable
  maxIdleConnections: 15
  maxLifetimeConnection: 5
  maxOpenConnections: 100
  maxIdleTimeConnection: 2
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  IdleCheckFrequency: 500
jwt:
  secret: mySecretKey


